- defaultTab: nodes
  description: |-
    Job para criar containers Docker com imagem do Nginx
    ## tech:

    - Docker
    - Nginx
    - Linux

    ### Este job tem um "Plugin Customizado" para criar Container.
  executionEnabled: true
  group: Docker
  id: fb482aea-2757-4537-a79a-41f064be458b
  loglevel: INFO
  name: Cria_Container_Docker
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - description: Verifica o Docker
      scriptfile: /home/weskley/my-plugins/verificaDocker.sh
    - configuration:
        host: '8081'
        image: nginx
        name: webserver
      description: Cria container Docker
      nodeStep: true
      type: docker
    - description: Mostra o Container
      scriptfile: /home/weskley/my-plugins/mostraContainer.sh
    keepgoing: false
    strategy: node-first
  uuid: fb482aea-2757-4537-a79a-41f064be458b

